### PR TITLE
leb128:add ReadVarUint64 function and fix overflow corner case

### LINKED ISSUE #175: Read leb128 fail when trying to read 64 bit of small number
```golang
r := bytes.NewReader([]byte{0x08})
n, err := ReadUint64(r)
if err != nil {
  t.Fatal(err)
}
fmt.Println(n)
// output: leb128: invalid uint
```

### PR DESCRIPTION
**Pull request by laizy**
Close #175

### CODE REVIEW

File: wasm/leb128/read_test.go [hunk 1]
```diff
@@ -217,6 +234,8 @@ func readVarUintRecur(r io.Reader, n uint) (uint64, error) {
 	}
 }
 
+// a less efficent recurrsive version but matches the spec defined in https://webassembly.github.io/spec/core/binary/values.html#integers
```
Comment (twitchyliquid64) [inline wasm/leb128/read_test.go]: s/recurrsive/recursive

Comment (laizy) [inline wasm/leb128/read_test.go]:
```suggestion
// a less efficent recursive version but matches the spec defined in https://webassembly.github.io/spec/core/binary/values.html#integers
```

File: wasm/leb128/read_test.go [hunk 2]
```diff
@@ -192,6 +206,8 @@ func TestCompareReadVarUint(t *testing.T) {
...
```
Comment (laizy) [inline wasm/leb128/read_test.go]:
```suggestion
// a less efficent recursive version but matches the spec defined in https://webassembly.github.io/spec/core/binary/values.html#integers
```
